# palette = "grey"
palette = "grey"
format = """$username$hostname$directory$fill[$all](grey)$time$line_break$character"""

[character]
success_symbol = "[@](bold green)"
error_symbol = "[@](bold red)"

[fill]
symbol = 'â”€'
style = "fill_style"

[cmd_duration]
min_time = 10000

[time]
disabled = false
time_format = "%F %T"
style = "time_style"
format = '[$time]($style)'

[python]
symbol = "py "

[package]
symbol = "package "
style = "package_style"

[git_branch]
symbol = "git "

[aws]
symbol = "aws "

[terraform]
symbol = "tf "
style = "bold terraform_style"

[palettes.grey]
grey = "#777777"
none = "#777777"
white = "#777777"
rosewater = "#777777"
fill_style = "#222222"
time_style = "#444444"
package_style = "#777777"
terraform_style = "#777777"
flamingo = "#777777"
pink = "#777777"
mauve = "#777777"
maroon = "#777777"
peach = "#777777"
sky = "#777777"
sapphire = "#777777"
blue = "#777777"
lavender = "#777777"
text = "#777777"
subtext1 = "#777777"
subtext0 = "#777777"
overlay2 = "#777777"
overlay1 = "#777777"
overlay0 = "#777777"
surface2 = "#777777"
surface1 = "#777777"
surface0 = "#777777"
base = "#777777"
mantle = "#777777"
crust = "#777777"
background = "#777777"
current_line = "#777777"
foreground = "#777777"
comment = "#777777"
cyan = "#777777"
green = "#777777"
orange = "#777777"
purple = "#777777"
red = "#777777"
yellow = "#777777"


[palettes.silver]
grey = "#C0C0C0"
none = "#C0C0C0"
white = "#C0C0C0"
rosewater = "#C0C0C0"
fill_style = "#6B6B6B"
time_style = "#8D8D8D"
package_style = "#C0C0C0"
terraform_style = "#C0C0C0"
flamingo = "#C0C0C0"
pink = "#C0C0C0"
mauve = "#C0C0C0"
maroon = "#C0C0C0"
peach = "#C0C0C0"
sky = "#C0C0C0"
sapphire = "#C0C0C0"
blue = "#C0C0C0"
lavender = "#C0C0C0"
text = "#C0C0C0"
subtext1 = "#C0C0C0"
subtext0 = "#C0C0C0"
overlay2 = "#C0C0C0"
overlay1 = "#C0C0C0"
overlay0 = "#C0C0C0"
surface2 = "#C0C0C0"
surface1 = "#C0C0C0"
surface0 = "#C0C0C0"
base = "#C0C0C0"
mantle = "#C0C0C0"
crust = "#C0C0C0"
background = "#C0C0C0"
current_line = "#C0C0C0"
foreground = "#C0C0C0"
comment = "#C0C0C0"
cyan = "#C0C0C0"
green = "#C0C0C0"
orange = "#C0C0C0"
purple = "#C0C0C0"
red = "#C0C0C0"
yellow = "#C0C0C0"

[palettes.lime]
grey = "#11FF00"
none = "#11FF00"
white = "#11FF00"
rosewater = "#11FF00"
fill_style = "#004400"
time_style = "#008800"
package_style = "#11FF00"
terraform_style = "#11FF00"
flamingo = "#11FF00"
pink = "#11FF00"
mauve = "#11FF00"
maroon = "#11FF00"
peach = "#11FF00"
sky = "#11FF00"
sapphire = "#11FF00"
blue = "#11FF00"
lavender = "#11FF00"
text = "#11FF00"
subtext1 = "#11FF00"
subtext0 = "#11FF00"
overlay2 = "#11FF00"
overlay1 = "#11FF00"
overlay0 = "#11FF00"
surface2 = "#11FF00"
surface1 = "#11FF00"
surface0 = "#11FF00"
base = "#11FF00"
mantle = "#11FF00"
crust = "#11FF00"
background = "#11FF00"
current_line = "#11FF00"
foreground = "#11FF00"
comment = "#11FF00"
cyan = "#11FF00"
green = "#11FF00"
orange = "#11FF00"
purple = "#11FF00"
red = "#11FF00"
yellow = "#11FF00"